/**
 * IELTS Vocabulary — English to Bangla translations
 * Common academic / IELTS words with Bangla meanings.
 */
const VOCABULARY = {
  // ---- A ----
  "absorb": { bangla: "শোষণ করা", type: "verb" },
  "absorbed": { bangla: "শোষিত", type: "adjective" },
  "academic": { bangla: "শিক্ষাগত", type: "adjective" },
  "acceptable": { bangla: "গ্রহণযোগ্য", type: "adjective" },
  "acceptance": { bangla: "স্বীকৃতি", type: "noun" },
  "accessible": { bangla: "সহজলভ্য", type: "adjective" },
  "accountability": { bangla: "জবাবদিহিতা", type: "noun" },
  "accurate": { bangla: "সঠিক", type: "adjective" },
  "accurately": { bangla: "সঠিকভাবে", type: "adverb" },
  "achieve": { bangla: "অর্জন করা", type: "verb" },
  "achieved": { bangla: "অর্জিত", type: "adjective" },
  "achievement": { bangla: "অর্জন", type: "noun" },
  "acknowledge": { bangla: "স্বীকার করা", type: "verb" },
  "addiction": { bangla: "আসক্তি", type: "noun" },
  "addictive": { bangla: "আসক্তিকর", type: "adjective" },
  "adequate": { bangla: "পর্যাপ্ত", type: "adjective" },
  "adequately": { bangla: "পর্যাপ্তভাবে", type: "adverb" },
  "adolescents": { bangla: "কিশোর-কিশোরী", type: "noun" },
  "advertise": { bangla: "বিজ্ঞাপন দেওয়া", type: "verb" },
  "advertising": { bangla: "বিজ্ঞাপন", type: "noun" },
  "advocate": { bangla: "সমর্থন করা", type: "verb" },
  "aesthetics": { bangla: "নান্দনিকতা", type: "noun" },
  "affect": { bangla: "প্রভাব ফেলা", type: "verb" },
  "affordable": { bangla: "সাশ্রয়ী", type: "adjective" },
  "aggression": { bangla: "আগ্রাসন", type: "noun" },
  "aggressive": { bangla: "আক্রমণাত্মক", type: "adjective" },
  "agriculture": { bangla: "কৃষি", type: "noun" },
  "aid": { bangla: "সহায়তা", type: "noun" },
  "allocate": { bangla: "বরাদ্দ করা", type: "verb" },
  "alternative": { bangla: "বিকল্প", type: "noun" },
  "ambition": { bangla: "উচ্চাকাঙ্ক্ষা", type: "noun" },
  "ambitious": { bangla: "উচ্চাকাঙ্ক্ষী", type: "adjective" },
  "analytical": { bangla: "বিশ্লেষণী", type: "adjective" },
  "anxiety": { bangla: "উদ্বেগ", type: "noun" },
  "appeal": { bangla: "আকর্ষণ; আবেদন", type: "noun" },
  "appealing": { bangla: "আকর্ষণীয়", type: "adjective" },
  "appearance": { bangla: "চেহারা; উপস্থিতি", type: "noun" },
  "appreciation": { bangla: "প্রশংসা", type: "noun" },
  "appropriate": { bangla: "উপযুক্ত", type: "adjective" },
  "appropriately": { bangla: "যথাযথভাবে", type: "adverb" },
  "artwork": { bangla: "শিল্পকর্ম", type: "noun" },
  "aspect": { bangla: "দিক; বিষয়", type: "noun" },
  "aspects": { bangla: "দিক; বিষয়", type: "noun" },
  "assertive": { bangla: "দৃঢ়প্রতিজ্ঞ", type: "adjective" },
  "assessment": { bangla: "মূল্যায়ন", type: "noun" },
  "athletes": { bangla: "ক্রীড়াবিদ", type: "noun" },
  "atmosphere": { bangla: "পরিবেশ; বায়ুমণ্ডল", type: "noun" },
  "attendance": { bangla: "উপস্থিতি", type: "noun" },
  "attitude": { bangla: "মনোভাব", type: "noun" },
  "attitudes": { bangla: "মনোভাব", type: "noun" },
  "attractions": { bangla: "আকর্ষণীয় স্থান", type: "noun" },
  "automation": { bangla: "স্বয়ংক্রিয়করণ", type: "noun" },
  "availability": { bangla: "প্রাপ্যতা", type: "noun" },
  "awareness": { bangla: "সচেতনতা", type: "noun" },
  // ---- B ----
  "barrier": { bangla: "বাধা", type: "noun" },
  "barriers": { bangla: "বাধা", type: "noun" },
  "behaviour": { bangla: "আচরণ", type: "noun" },
  "beneficial": { bangla: "উপকারী", type: "adjective" },
  "bias": { bangla: "পক্ষপাত", type: "noun" },
  "bilingual": { bangla: "দ্বিভাষিক", type: "adjective" },
  "biodiversity": { bangla: "জীববৈচিত্র্য", type: "noun" },
  "bond": { bangla: "বন্ধন", type: "noun" },
  "bonds": { bangla: "বন্ধন", type: "noun" },
  "boost": { bangla: "বাড়ানো; উৎসাহিত করা", type: "verb" },
  "boundaries": { bangla: "সীমানা", type: "noun" },
  "brand": { bangla: "ব্র্যান্ড", type: "noun" },
  "breakthrough": { bangla: "যুগান্তকারী আবিষ্কার", type: "noun" },
  "broadcasting": { bangla: "সম্প্রচার", type: "noun" },
  "broaden": { bangla: "প্রসারিত করা", type: "verb" },
  "budget": { bangla: "বাজেট", type: "noun" },
  "bullying": { bangla: "উৎপীড়ন", type: "noun" },
  "burden": { bangla: "বোঝা", type: "noun" },
  "burnout": { bangla: "পরিশ্রান্তি; মানসিক ক্লান্তি", type: "noun" },
  // ---- C ----
  "calorie": { bangla: "ক্যালোরি", type: "noun" },
  "campaigns": { bangla: "প্রচারণা", type: "noun" },
  "candidate": { bangla: "প্রার্থী", type: "noun" },
  "candidates": { bangla: "প্রার্থী", type: "noun" },
  "capable": { bangla: "সক্ষম", type: "adjective" },
  "capacity": { bangla: "ক্ষমতা", type: "noun" },
  "carbon": { bangla: "কার্বন", type: "noun" },
  "career": { bangla: "পেশা; কর্মজীবন", type: "noun" },
  "celebrities": { bangla: "বিখ্যাত ব্যক্তি", type: "noun" },
  "celebrity": { bangla: "বিখ্যাত ব্যক্তি", type: "noun" },
  "challenge": { bangla: "কঠিন কাজ; চ্যালেঞ্জ", type: "noun" },
  "childcare": { bangla: "শিশুযত্ন", type: "noun" },
  "cholesterol": { bangla: "কোলেস্টেরল", type: "noun" },
  "chronic": { bangla: "দীর্ঘস্থায়ী", type: "adjective" },
  "circulation": { bangla: "প্রচার; প্রচলন", type: "noun" },
  "circumstances": { bangla: "পরিস্থিতি", type: "noun" },
  "citizens": { bangla: "নাগরিক", type: "noun" },
  "civic": { bangla: "নাগরিক", type: "adjective" },
  "climate": { bangla: "জলবায়ু", type: "noun" },
  "cognitive": { bangla: "জ্ঞানীয়", type: "adjective" },
  "collaboration": { bangla: "সহযোগিতা", type: "noun" },
  "colleagues": { bangla: "সহকর্মী", type: "noun" },
  "combination": { bangla: "সংমিশ্রণ", type: "noun" },
  "commerce": { bangla: "বাণিজ্য", type: "noun" },
  "commit": { bangla: "অঙ্গীকার করা", type: "verb" },
  "commitment": { bangla: "অঙ্গীকার", type: "noun" },
  "communicate": { bangla: "যোগাযোগ করা", type: "verb" },
  "communication": { bangla: "যোগাযোগ", type: "noun" },
  "community": { bangla: "সম্প্রদায়", type: "noun" },
  "commute": { bangla: "যাতায়াত", type: "noun" },
  "comparison": { bangla: "তুলনা", type: "noun" },
  "compelling": { bangla: "বাধ্যতামূলক", type: "adjective" },
  "compensation": { bangla: "ক্ষতিপূরণ", type: "noun" },
  "compete": { bangla: "প্রতিযোগিতা করা", type: "verb" },
  "competition": { bangla: "প্রতিযোগিতা", type: "noun" },
  "competitive": { bangla: "প্রতিযোগিতামূলক", type: "adjective" },
  "complex": { bangla: "জটিল", type: "adjective" },
  "comprehension": { bangla: "বোধগম্যতা", type: "noun" },
  "compromise": { bangla: "আপস", type: "noun" },
  "compulsory": { bangla: "বাধ্যতামূলক", type: "adjective" },
  "concentrate": { bangla: "মনোযোগ দেওয়া", type: "verb" },
  "concepts": { bangla: "ধারণা", type: "noun" },
  "confidence": { bangla: "আত্মবিশ্বাস", type: "noun" },
  "confident": { bangla: "আত্মবিশ্বাসী", type: "adjective" },
  "conflict": { bangla: "দ্বন্দ্ব", type: "noun" },
  "congestion": { bangla: "যানজট", type: "noun" },
  "connect": { bangla: "সংযুক্ত করা", type: "verb" },
  "connectivity": { bangla: "সংযোগ", type: "noun" },
  "conscious": { bangla: "সচেতন", type: "adjective" },
  "consequences": { bangla: "পরিণতি", type: "noun" },
  "consequently": { bangla: "ফলস্বরূপ", type: "adverb" },
  "conservation": { bangla: "সংরক্ষণ", type: "noun" },
  "considerable": { bangla: "যথেষ্ট", type: "adjective" },
  "consistent": { bangla: "ধারাবাহিক", type: "adjective" },
  "consistently": { bangla: "ধারাবাহিকভাবে", type: "adverb" },
  "constantly": { bangla: "ক্রমাগত", type: "adverb" },
  "constraints": { bangla: "সীমাবদ্ধতা", type: "noun" },
  "construction": { bangla: "নির্মাণ", type: "noun" },
  "consume": { bangla: "ভোগ করা", type: "verb" },
  "consumer": { bangla: "ভোক্তা", type: "noun" },
  "consumption": { bangla: "ভোগ; ব্যবহার", type: "noun" },
  "content": { bangla: "বিষয়বস্তু", type: "noun" },
  "context": { bangla: "প্রেক্ষাপট", type: "noun" },
  "contribute": { bangla: "অবদান রাখা", type: "verb" },
  "controversial": { bangla: "বিতর্কিত", type: "adjective" },
  "convenient": { bangla: "সুবিধাজনক", type: "adjective" },
  "conventional": { bangla: "প্রচলিত", type: "adjective" },
  "convey": { bangla: "প্রকাশ করা; জানানো", type: "verb" },
  "cooperation": { bangla: "সহযোগিতা", type: "noun" },
  "corruption": { bangla: "দুর্নীতি", type: "noun" },
  "coverage": { bangla: "সংবাদ প্রতিবেদন", type: "noun" },
  "creative": { bangla: "সৃজনশীল", type: "adjective" },
  "creativity": { bangla: "সৃজনশীলতা", type: "noun" },
  "credible": { bangla: "বিশ্বাসযোগ্য", type: "adjective" },
  "crime": { bangla: "অপরাধ", type: "noun" },
  "criminal": { bangla: "অপরাধী", type: "noun" },
  "critical": { bangla: "সমালোচনামূলক", type: "adjective" },
  "critics": { bangla: "সমালোচক", type: "noun" },
  "crucial": { bangla: "অত্যন্ত গুরুত্বপূর্ণ", type: "adjective" },
  "culinary": { bangla: "রান্না সংক্রান্ত", type: "adjective" },
  "cultural": { bangla: "সাংস্কৃতিক", type: "adjective" },
  "culture": { bangla: "সংস্কৃতি", type: "noun" },
  "curiosity": { bangla: "কৌতূহল", type: "noun" },
  "curriculum": { bangla: "পাঠ্যক্রম", type: "noun" },
  "cyberbullying": { bangla: "সাইবার হয়রানি", type: "noun" },
  // ---- D ----
  "debate": { bangla: "বিতর্ক", type: "noun" },
  "debt": { bangla: "ঋণ", type: "noun" },
  "decades": { bangla: "দশক", type: "noun" },
  "decline": { bangla: "হ্রাস", type: "noun" },
  "dedication": { bangla: "নিষ্ঠা", type: "noun" },
  "defence": { bangla: "প্রতিরক্ষা", type: "noun" },
  "deficiencies": { bangla: "ঘাটতি", type: "noun" },
  "deforestation": { bangla: "বন উজাড়", type: "noun" },
  "deliberately": { bangla: "ইচ্ছাকৃতভাবে", type: "adverb" },
  "demand": { bangla: "চাহিদা", type: "noun" },
  "demonstrate": { bangla: "প্রদর্শন করা", type: "verb" },
  "dependence": { bangla: "নির্ভরতা", type: "noun" },
  "dependent": { bangla: "নির্ভরশীল", type: "adjective" },
  "depression": { bangla: "বিষণ্ণতা", type: "noun" },
  "depth": { bangla: "গভীরতা", type: "noun" },
  "desensitised": { bangla: "সংবেদনশূন্য", type: "adjective" },
  "deserve": { bangla: "প্রাপ্য হওয়া", type: "verb" },
  "despite": { bangla: "সত্ত্বেও", type: "preposition" },
  "determination": { bangla: "সংকল্প", type: "noun" },
  "deterrent": { bangla: "প্রতিরোধক", type: "noun" },
  "detrimental": { bangla: "ক্ষতিকর", type: "adjective" },
  "devastating": { bangla: "ধ্বংসাত্মক", type: "adjective" },
  "development": { bangla: "উন্নয়ন", type: "noun" },
  "device": { bangla: "যন্ত্র", type: "noun" },
  "diabetes": { bangla: "ডায়াবেটিস", type: "noun" },
  "diet": { bangla: "খাদ্যাভ্যাস", type: "noun" },
  "dietary": { bangla: "খাদ্য সংক্রান্ত", type: "adjective" },
  "digital": { bangla: "ডিজিটাল", type: "adjective" },
  "diplomacy": { bangla: "কূটনীতি", type: "noun" },
  "disabled": { bangla: "প্রতিবন্ধী", type: "adjective" },
  "disadvantage": { bangla: "অসুবিধা", type: "noun" },
  "disadvantaged": { bangla: "সুবিধাবঞ্চিত", type: "adjective" },
  "disappear": { bangla: "অদৃশ্য হওয়া", type: "verb" },
  "discipline": { bangla: "শৃঙ্খলা", type: "noun" },
  "discourage": { bangla: "নিরুৎসাহিত করা", type: "verb" },
  "discrimination": { bangla: "বৈষম্য", type: "noun" },
  "disease": { bangla: "রোগ", type: "noun" },
  "disrupt": { bangla: "ব্যাহত করা", type: "verb" },
  "disruptive": { bangla: "বিঘ্নকারী", type: "adjective" },
  "distinguish": { bangla: "পার্থক্য করা", type: "verb" },
  "diverse": { bangla: "বৈচিত্র্যময়", type: "adjective" },
  "diversity": { bangla: "বৈচিত্র্য", type: "noun" },
  "domestic": { bangla: "দেশীয়; গার্হস্থ্য", type: "adjective" },
  "donation": { bangla: "দান", type: "noun" },
  "drawbacks": { bangla: "অসুবিধা", type: "noun" },
  "drought": { bangla: "খরা", type: "noun" },
  // ---- E ----
  "earnings": { bangla: "আয়", type: "noun" },
  "economic": { bangla: "অর্থনৈতিক", type: "adjective" },
  "economy": { bangla: "অর্থনীতি", type: "noun" },
  "ecosystem": { bangla: "বাস্তুতন্ত্র", type: "noun" },
  "educational": { bangla: "শিক্ষামূলক", type: "adjective" },
  "effective": { bangla: "কার্যকর", type: "adjective" },
  "efficiency": { bangla: "কার্যকারিতা", type: "noun" },
  "efficient": { bangla: "দক্ষ", type: "adjective" },
  "effort": { bangla: "প্রচেষ্টা", type: "noun" },
  "efforts": { bangla: "প্রচেষ্টা", type: "noun" },
  "elderly": { bangla: "বয়স্ক", type: "adjective" },
  "eliminate": { bangla: "নির্মূল করা", type: "verb" },
  "emissions": { bangla: "নির্গমন", type: "noun" },
  "emotional": { bangla: "আবেগপূর্ণ", type: "adjective" },
  "emotions": { bangla: "আবেগ", type: "noun" },
  "empathy": { bangla: "সহানুভূতি", type: "noun" },
  "emphasis": { bangla: "জোর", type: "noun" },
  "employee": { bangla: "কর্মচারী", type: "noun" },
  "employer": { bangla: "নিয়োগকর্তা", type: "noun" },
  "employment": { bangla: "কর্মসংস্থান", type: "noun" },
  "encounter": { bangla: "সম্মুখীন হওয়া", type: "verb" },
  "encouragement": { bangla: "উৎসাহ", type: "noun" },
  "endangered": { bangla: "বিপন্ন", type: "adjective" },
  "enforce": { bangla: "প্রয়োগ করা", type: "verb" },
  "enforcement": { bangla: "প্রয়োগ", type: "noun" },
  "engage": { bangla: "জড়িত করা", type: "verb" },
  "enhance": { bangla: "উন্নত করা", type: "verb" },
  "enormous": { bangla: "বিশাল", type: "adjective" },
  "enrich": { bangla: "সমৃদ্ধ করা", type: "verb" },
  "entertainment": { bangla: "বিনোদন", type: "noun" },
  "enthusiasm": { bangla: "উৎসাহ", type: "noun" },
  "entirely": { bangla: "সম্পূর্ণরূপে", type: "adverb" },
  "entrepreneurs": { bangla: "উদ্যোক্তা", type: "noun" },
  "environment": { bangla: "পরিবেশ", type: "noun" },
  "environmental": { bangla: "পরিবেশগত", type: "adjective" },
  "equality": { bangla: "সমতা", type: "noun" },
  "equipment": { bangla: "সরঞ্জাম", type: "noun" },
  "essential": { bangla: "অপরিহার্য", type: "adjective" },
  "evaluate": { bangla: "মূল্যায়ন করা", type: "verb" },
  "eventually": { bangla: "অবশেষে", type: "adverb" },
  "evidence": { bangla: "প্রমাণ", type: "noun" },
  "evident": { bangla: "স্পষ্ট", type: "adjective" },
  "exams": { bangla: "পরীক্ষা", type: "noun" },
  "excessive": { bangla: "অত্যধিক", type: "adjective" },
  "exclusively": { bangla: "একচেটিয়াভাবে", type: "adverb" },
  "exhibition": { bangla: "প্রদর্শনী", type: "noun" },
  "expand": { bangla: "সম্প্রসারিত করা", type: "verb" },
  "expansion": { bangla: "সম্প্রসারণ", type: "noun" },
  "expectation": { bangla: "প্রত্যাশা", type: "noun" },
  "expectations": { bangla: "প্রত্যাশা", type: "noun" },
  "expense": { bangla: "ব্যয়", type: "noun" },
  "expertise": { bangla: "দক্ষতা", type: "noun" },
  "exploitation": { bangla: "শোষণ", type: "noun" },
  "exploration": { bangla: "অনুসন্ধান", type: "noun" },
  "expose": { bangla: "উন্মুক্ত করা", type: "verb" },
  "exposure": { bangla: "সংস্পর্শ", type: "noun" },
  "expression": { bangla: "অভিব্যক্তি", type: "noun" },
  "extensive": { bangla: "ব্যাপক", type: "adjective" },
  "extent": { bangla: "পরিমাণ; মাত্রা", type: "noun" },
  "external": { bangla: "বাহ্যিক", type: "adjective" },
  "extinct": { bangla: "বিলুপ্ত", type: "adjective" },
  "extinction": { bangla: "বিলুপ্তি", type: "noun" },
  "extreme": { bangla: "চরম", type: "adjective" },
  "extremely": { bangla: "অত্যন্ত", type: "adverb" },
  // ---- F ----
  "facilities": { bangla: "সুবিধা", type: "noun" },
  "facility": { bangla: "সুবিধা", type: "noun" },
  "factor": { bangla: "কারণ", type: "noun" },
  "factors": { bangla: "কারণ", type: "noun" },
  "familiar": { bangla: "পরিচিত", type: "adjective" },
  "financial": { bangla: "আর্থিক", type: "adjective" },
  "fitness": { bangla: "শারীরিক সুস্থতা", type: "noun" },
  "flexibility": { bangla: "নমনীয়তা", type: "noun" },
  "flexible": { bangla: "নমনীয়", type: "adjective" },
  "fluency": { bangla: "সাবলীলতা", type: "noun" },
  "fluent": { bangla: "সাবলীল", type: "adjective" },
  "focus": { bangla: "মনোযোগ", type: "noun" },
  "forced": { bangla: "বাধ্য করা", type: "adjective" },
  "foreign": { bangla: "বিদেশি", type: "adjective" },
  "forest": { bangla: "বন", type: "noun" },
  "forests": { bangla: "বন", type: "noun" },
  "fossil": { bangla: "জীবাশ্ম", type: "noun" },
  "foundation": { bangla: "ভিত্তি", type: "noun" },
  "fraud": { bangla: "প্রতারণা", type: "noun" },
  "freedom": { bangla: "স্বাধীনতা", type: "noun" },
  "frequently": { bangla: "প্রায়ই", type: "adverb" },
  "freshness": { bangla: "সতেজতা", type: "noun" },
  "fulfil": { bangla: "পূরণ করা", type: "verb" },
  "fundamental": { bangla: "মৌলিক", type: "adjective" },
  "funding": { bangla: "অর্থায়ন", type: "noun" },
  "furthermore": { bangla: "তদুপরি", type: "adverb" },
  // ---- G ----
  "gender": { bangla: "লিঙ্গ", type: "noun" },
  "generate": { bangla: "উৎপন্ন করা", type: "verb" },
  "generation": { bangla: "প্রজন্ম", type: "noun" },
  "generations": { bangla: "প্রজন্ম", type: "noun" },
  "genuine": { bangla: "প্রকৃত", type: "adjective" },
  "genuinely": { bangla: "প্রকৃতপক্ষে", type: "adverb" },
  "global": { bangla: "বৈশ্বিক", type: "adjective" },
  "globalisation": { bangla: "বিশ্বায়ন", type: "noun" },
  "governance": { bangla: "শাসন", type: "noun" },
  "government": { bangla: "সরকার", type: "noun" },
  "governments": { bangla: "সরকার", type: "noun" },
  "gradually": { bangla: "ধীরে ধীরে", type: "adverb" },
  "graduate": { bangla: "স্নাতক", type: "noun" },
  "graduates": { bangla: "স্নাতক", type: "noun" },
  "grants": { bangla: "অনুদান", type: "noun" },
  "guarantee": { bangla: "নিশ্চয়তা", type: "noun" },
  "guidance": { bangla: "নির্দেশনা", type: "noun" },
  // ---- H ----
  "habitat": { bangla: "আবাসস্থল", type: "noun" },
  "habits": { bangla: "অভ্যাস", type: "noun" },
  "hardship": { bangla: "কষ্ট", type: "noun" },
  "harsh": { bangla: "কঠোর", type: "adjective" },
  "hazardous": { bangla: "বিপজ্জনক", type: "adjective" },
  "healthcare": { bangla: "স্বাস্থ্যসেবা", type: "noun" },
  "heritage": { bangla: "ঐতিহ্য", type: "noun" },
  "historic": { bangla: "ঐতিহাসিক", type: "adjective" },
  "homelessness": { bangla: "গৃহহীনতা", type: "noun" },
  "household": { bangla: "গৃহস্থালি", type: "noun" },
  "housing": { bangla: "আবাসন", type: "noun" },
  "humanitarian": { bangla: "মানবিক", type: "adjective" },
  // ---- I ----
  "identity": { bangla: "পরিচয়", type: "noun" },
  "illegal": { bangla: "অবৈধ", type: "adjective" },
  "illness": { bangla: "অসুস্থতা", type: "noun" },
  "illnesses": { bangla: "অসুস্থতা", type: "noun" },
  "impact": { bangla: "প্রভাব", type: "noun" },
  "implement": { bangla: "বাস্তবায়ন করা", type: "verb" },
  "implementation": { bangla: "বাস্তবায়ন", type: "noun" },
  "implications": { bangla: "প্রভাব", type: "noun" },
  "impression": { bangla: "ছাপ; ধারণা", type: "noun" },
  "imprisonment": { bangla: "কারাদণ্ড", type: "noun" },
  "inadequate": { bangla: "অপর্যাপ্ত", type: "adjective" },
  "incentive": { bangla: "প্রণোদনা", type: "noun" },
  "income": { bangla: "আয়", type: "noun" },
  "increase": { bangla: "বৃদ্ধি", type: "noun" },
  "increasingly": { bangla: "ক্রমবর্ধমানভাবে", type: "adverb" },
  "independence": { bangla: "স্বাধীনতা", type: "noun" },
  "individual": { bangla: "ব্যক্তি", type: "noun" },
  "industry": { bangla: "শিল্প", type: "noun" },
  "inequality": { bangla: "বৈষম্য", type: "noun" },
  "influence": { bangla: "প্রভাব", type: "noun" },
  "infrastructure": { bangla: "অবকাঠামো", type: "noun" },
  "initial": { bangla: "প্রাথমিক", type: "adjective" },
  "initiative": { bangla: "উদ্যোগ", type: "noun" },
  "initiatives": { bangla: "উদ্যোগ", type: "noun" },
  "injury": { bangla: "আঘাত", type: "noun" },
  "innovation": { bangla: "উদ্ভাবন", type: "noun" },
  "innovative": { bangla: "উদ্ভাবনী", type: "adjective" },
  "insight": { bangla: "অন্তর্দৃষ্টি", type: "noun" },
  "inspiration": { bangla: "অনুপ্রেরণা", type: "noun" },
  "inspiring": { bangla: "অনুপ্রেরণাদায়ক", type: "adjective" },
  "instilled": { bangla: "জাগ্রত করা", type: "verb" },
  "institutions": { bangla: "প্রতিষ্ঠান", type: "noun" },
  "insufficient": { bangla: "অপর্যাপ্ত", type: "adjective" },
  "integration": { bangla: "একীকরণ", type: "noun" },
  "intellectual": { bangla: "বুদ্ধিবৃত্তিক", type: "adjective" },
  "intelligence": { bangla: "বুদ্ধিমত্তা", type: "noun" },
  "intelligent": { bangla: "বুদ্ধিমান", type: "adjective" },
  "intense": { bangla: "তীব্র", type: "adjective" },
  "interact": { bangla: "মিথস্ক্রিয়া করা", type: "verb" },
  "interaction": { bangla: "মিথস্ক্রিয়া", type: "noun" },
  "interpretation": { bangla: "ব্যাখ্যা", type: "noun" },
  "intervention": { bangla: "হস্তক্ষেপ", type: "noun" },
  "investment": { bangla: "বিনিয়োগ", type: "noun" },
  "involve": { bangla: "জড়িত করা", type: "verb" },
  "involvement": { bangla: "সম্পৃক্ততা", type: "noun" },
  "irrigation": { bangla: "সেচ", type: "noun" },
  "isolated": { bangla: "বিচ্ছিন্ন", type: "adjective" },
  "isolation": { bangla: "বিচ্ছিন্নতা", type: "noun" },
  // ---- J ----
  "journeys": { bangla: "যাত্রা", type: "noun" },
  "judgement": { bangla: "বিচার; রায়", type: "noun" },
  "justice": { bangla: "ন্যায়বিচার", type: "noun" },
  "justified": { bangla: "যুক্তিসঙ্গত", type: "adjective" },
  "justify": { bangla: "ন্যায্যতা প্রমাণ করা", type: "verb" },
  "juvenile": { bangla: "কিশোর", type: "adjective" },
  // ---- L ----
  "lasting": { bangla: "দীর্ঘস্থায়ী", type: "adjective" },
  "leadership": { bangla: "নেতৃত্ব", type: "noun" },
  "legislation": { bangla: "আইন", type: "noun" },
  "leisure": { bangla: "অবসর", type: "noun" },
  "lifestyle": { bangla: "জীবনযাত্রা", type: "noun" },
  "likelihood": { bangla: "সম্ভাবনা", type: "noun" },
  "limit": { bangla: "সীমা", type: "noun" },
  "limits": { bangla: "সীমা", type: "noun" },
  "literacy": { bangla: "সাক্ষরতা", type: "noun" },
  "literature": { bangla: "সাহিত্য", type: "noun" },
  "loneliness": { bangla: "একাকীত্ব", type: "noun" },
  "luxury": { bangla: "বিলাসিতা", type: "noun" },
  // ---- M ----
  "maintain": { bangla: "বজায় রাখা", type: "verb" },
  "maintenance": { bangla: "রক্ষণাবেক্ষণ", type: "noun" },
  "management": { bangla: "ব্যবস্থাপনা", type: "noun" },
  "manager": { bangla: "ব্যবস্থাপক", type: "noun" },
  "managers": { bangla: "ব্যবস্থাপক", type: "noun" },
  "mandatory": { bangla: "বাধ্যতামূলক", type: "adjective" },
  "manners": { bangla: "শিষ্টাচার", type: "noun" },
  "manufacturers": { bangla: "নির্মাতা", type: "noun" },
  "marketing": { bangla: "বিপণন", type: "noun" },
  "marriage": { bangla: "বিবাহ", type: "noun" },
  "meaningful": { bangla: "অর্থবহ", type: "adjective" },
  "meanwhile": { bangla: "এদিকে", type: "adverb" },
  "measure": { bangla: "ব্যবস্থা", type: "noun" },
  "measures": { bangla: "ব্যবস্থা", type: "noun" },
  "media": { bangla: "গণমাধ্যম", type: "noun" },
  "medication": { bangla: "ওষুধ", type: "noun" },
  "mental": { bangla: "মানসিক", type: "adjective" },
  "mentally": { bangla: "মানসিকভাবে", type: "adverb" },
  "mentorship": { bangla: "পরামর্শদান", type: "noun" },
  "merit": { bangla: "যোগ্যতা", type: "noun" },
  "migration": { bangla: "অভিবাসন", type: "noun" },
  "military": { bangla: "সামরিক", type: "adjective" },
  "minority": { bangla: "সংখ্যালঘু", type: "noun" },
  "misleading": { bangla: "বিভ্রান্তিকর", type: "adjective" },
  "misunderstandings": { bangla: "ভুল বোঝাবুঝি", type: "noun" },
  "mobility": { bangla: "গতিশীলতা", type: "noun" },
  "moderation": { bangla: "পরিমিতি", type: "noun" },
  "moral": { bangla: "নৈতিক", type: "adjective" },
  "moreover": { bangla: "তাছাড়া", type: "adverb" },
  "mortgage": { bangla: "বন্ধকী ঋণ", type: "noun" },
  "motivate": { bangla: "অনুপ্রাণিত করা", type: "verb" },
  "motivated": { bangla: "অনুপ্রাণিত", type: "adjective" },
  "motivation": { bangla: "অনুপ্রেরণা", type: "noun" },
  "movement": { bangla: "আন্দোলন", type: "noun" },
  "multiple": { bangla: "একাধিক", type: "adjective" },
  "museum": { bangla: "জাদুঘর", type: "noun" },
  "mutual": { bangla: "পারস্পরিক", type: "adjective" },
  // ---- N ----
  "nation": { bangla: "জাতি", type: "noun" },
  "nations": { bangla: "জাতি", type: "noun" },
  "necessarily": { bangla: "অগত্যা", type: "adverb" },
  "necessity": { bangla: "প্রয়োজনীয়তা", type: "noun" },
  "negative": { bangla: "নেতিবাচক", type: "adjective" },
  "neglected": { bangla: "উপেক্ষিত", type: "adjective" },
  "negotiation": { bangla: "আলোচনা", type: "noun" },
  "neighbourhood": { bangla: "পাড়া-প্রতিবেশ", type: "noun" },
  "nevertheless": { bangla: "তবুও", type: "adverb" },
  "notable": { bangla: "উল্লেখযোগ্য", type: "adjective" },
  "noticeable": { bangla: "লক্ষণীয়", type: "adjective" },
  "novels": { bangla: "উপন্যাস", type: "noun" },
  "numeracy": { bangla: "সংখ্যাজ্ঞান", type: "noun" },
  "numerous": { bangla: "অসংখ্য", type: "adjective" },
  "nurture": { bangla: "লালন করা", type: "verb" },
  "nutrient": { bangla: "পুষ্টি উপাদান", type: "noun" },
  "nutrition": { bangla: "পুষ্টি", type: "noun" },
  // ---- O ----
  "obesity": { bangla: "স্থূলতা", type: "noun" },
  "obligation": { bangla: "বাধ্যবাধকতা", type: "noun" },
  "occasionally": { bangla: "মাঝে মাঝে", type: "adverb" },
  "offences": { bangla: "অপরাধ", type: "noun" },
  "offender": { bangla: "অপরাধী", type: "noun" },
  "opportunity": { bangla: "সুযোগ", type: "noun" },
  "optional": { bangla: "ঐচ্ছিক", type: "adjective" },
  "organisations": { bangla: "সংগঠন", type: "noun" },
  "outcome": { bangla: "ফলাফল", type: "noun" },
  "outcomes": { bangla: "ফলাফল", type: "noun" },
  "outdated": { bangla: "সেকেলে", type: "adjective" },
  "outweigh": { bangla: "অতিক্রম করা", type: "verb" },
  "overcrowding": { bangla: "অতিরিক্ত ভিড়", type: "noun" },
  "overlook": { bangla: "উপেক্ষা করা", type: "verb" },
  "overlooked": { bangla: "উপেক্ষিত; অবহেলিত", type: "adjective" },
  "overpopulation": { bangla: "অতিরিক্ত জনসংখ্যা", type: "noun" },
  "overweight": { bangla: "অতিরিক্ত ওজনবিশিষ্ট", type: "adjective" },
  "overwhelmed": { bangla: "অভিভূত", type: "adjective" },
  // ---- P ----
  "parental": { bangla: "পিতামাতার", type: "adjective" },
  "parenting": { bangla: "সন্তান প্রতিপালন", type: "noun" },
  "participants": { bangla: "অংশগ্রহণকারী", type: "noun" },
  "participate": { bangla: "অংশগ্রহণ করা", type: "verb" },
  "participation": { bangla: "অংশগ্রহণ", type: "noun" },
  "particular": { bangla: "বিশেষ", type: "adjective" },
  "particularly": { bangla: "বিশেষত", type: "adverb" },
  "passion": { bangla: "অনুরাগ", type: "noun" },
  "pastime": { bangla: "অবসর বিনোদন", type: "noun" },
  "patience": { bangla: "ধৈর্য", type: "noun" },
  "patient": { bangla: "রোগী", type: "noun" },
  "patients": { bangla: "রোগী", type: "noun" },
  "pattern": { bangla: "নিদর্শন; ধরন", type: "noun" },
  "patterns": { bangla: "নিদর্শন; ধরন", type: "noun" },
  "peaceful": { bangla: "শান্তিপূর্ণ", type: "adjective" },
  "peer": { bangla: "সমবয়সী", type: "noun" },
  "peers": { bangla: "সমবয়সী", type: "noun" },
  "penalties": { bangla: "জরিমানা; শাস্তি", type: "noun" },
  "penalty": { bangla: "জরিমানা; শাস্তি", type: "noun" },
  "perceive": { bangla: "উপলব্ধি করা", type: "verb" },
  "perform": { bangla: "সম্পাদন করা", type: "verb" },
  "performance": { bangla: "কর্মক্ষমতা", type: "noun" },
  "permanent": { bangla: "স্থায়ী", type: "adjective" },
  "perseverance": { bangla: "অধ্যবসায়", type: "noun" },
  "persistence": { bangla: "অধ্যবসায়", type: "noun" },
  "personality": { bangla: "ব্যক্তিত্ব", type: "noun" },
  "perspective": { bangla: "দৃষ্টিভঙ্গি", type: "noun" },
  "persuasive": { bangla: "প্ররোচনামূলক", type: "adjective" },
  "phenomenon": { bangla: "ঘটনা", type: "noun" },
  "physical": { bangla: "শারীরিক", type: "adjective" },
  "physically": { bangla: "শারীরিকভাবে", type: "adverb" },
  "planet": { bangla: "গ্রহ", type: "noun" },
  "platforms": { bangla: "প্ল্যাটফর্ম; মঞ্চ", type: "noun" },
  "poaching": { bangla: "চোরাই শিকার", type: "noun" },
  "policies": { bangla: "নীতি", type: "noun" },
  "policy": { bangla: "নীতি", type: "noun" },
  "political": { bangla: "রাজনৈতিক", type: "adjective" },
  "politician": { bangla: "রাজনীতিবিদ", type: "noun" },
  "politicians": { bangla: "রাজনীতিবিদ", type: "noun" },
  "politics": { bangla: "রাজনীতি", type: "noun" },
  "pollution": { bangla: "দূষণ", type: "noun" },
  "popularity": { bangla: "জনপ্রিয়তা", type: "noun" },
  "population": { bangla: "জনসংখ্যা", type: "noun" },
  "positive": { bangla: "ইতিবাচক", type: "adjective" },
  "potential": { bangla: "সম্ভাব্য", type: "adjective" },
  "poverty": { bangla: "দারিদ্র্য", type: "noun" },
  "practical": { bangla: "ব্যবহারিক", type: "adjective" },
  "predict": { bangla: "ভবিষ্যদ্বাণী করা", type: "verb" },
  "predominantly": { bangla: "প্রধানত", type: "adverb" },
  "prepared": { bangla: "প্রস্তুত", type: "adjective" },
  "presence": { bangla: "উপস্থিতি", type: "noun" },
  "preservation": { bangla: "সংরক্ষণ", type: "noun" },
  "preserve": { bangla: "সংরক্ষণ করা", type: "verb" },
  "press": { bangla: "সংবাদমাধ্যম", type: "noun" },
  "pressure": { bangla: "চাপ", type: "noun" },
  "prevent": { bangla: "প্রতিরোধ করা", type: "verb" },
  "prevention": { bangla: "প্রতিরোধ", type: "noun" },
  "previous": { bangla: "পূর্ববর্তী", type: "adjective" },
  "primarily": { bangla: "প্রধানত", type: "adverb" },
  "prioritise": { bangla: "অগ্রাধিকার দেওয়া", type: "verb" },
  "priority": { bangla: "অগ্রাধিকার", type: "noun" },
  "prison": { bangla: "কারাগার", type: "noun" },
  "privacy": { bangla: "গোপনীয়তা", type: "noun" },
  "procedures": { bangla: "পদ্ধতি", type: "noun" },
  "processed": { bangla: "প্রক্রিয়াজাত", type: "adjective" },
  "produce": { bangla: "উৎপাদন করা", type: "verb" },
  "productivity": { bangla: "উৎপাদনশীলতা", type: "noun" },
  "profession": { bangla: "পেশা", type: "noun" },
  "professional": { bangla: "পেশাদার", type: "adjective" },
  "professionals": { bangla: "পেশাদার", type: "noun" },
  "proficiency": { bangla: "দক্ষতা", type: "noun" },
  "profit": { bangla: "মুনাফা", type: "noun" },
  "programme": { bangla: "কর্মসূচি", type: "noun" },
  "programmes": { bangla: "কর্মসূচি", type: "noun" },
  "progress": { bangla: "অগ্রগতি", type: "noun" },
  "promote": { bangla: "প্রচার করা; উন্নীত করা", type: "verb" },
  "promotion": { bangla: "পদোন্নতি", type: "noun" },
  "property": { bangla: "সম্পত্তি", type: "noun" },
  "prospects": { bangla: "সম্ভাবনা", type: "noun" },
  "prosperity": { bangla: "সমৃদ্ধি", type: "noun" },
  "protection": { bangla: "সুরক্ষা", type: "noun" },
  "psychological": { bangla: "মনস্তাত্ত্বিক", type: "adjective" },
  "punishment": { bangla: "শাস্তি", type: "noun" },
  "purchase": { bangla: "ক্রয়", type: "noun" },
  "pursue": { bangla: "অনুসরণ করা", type: "verb" },
  // ---- Q ----
  "qualifications": { bangla: "যোগ্যতা", type: "noun" },
  "qualified": { bangla: "যোগ্য", type: "adjective" },
  "quantity": { bangla: "পরিমাণ", type: "noun" },
  // ---- R ----
  "rapid": { bangla: "দ্রুত", type: "adjective" },
  "rapidly": { bangla: "দ্রুতগতিতে", type: "adverb" },
  "rationale": { bangla: "যুক্তি", type: "noun" },
  "realistic": { bangla: "বাস্তবসম্মত", type: "adjective" },
  "reality": { bangla: "বাস্তবতা", type: "noun" },
  "recognise": { bangla: "চিনতে পারা", type: "verb" },
  "recognition": { bangla: "স্বীকৃতি", type: "noun" },
  "recommendations": { bangla: "সুপারিশ", type: "noun" },
  "recycling": { bangla: "পুনর্ব্যবহার", type: "noun" },
  "reduce": { bangla: "কমানো", type: "verb" },
  "reduction": { bangla: "হ্রাস", type: "noun" },
  "reflect": { bangla: "প্রতিফলিত করা", type: "verb" },
  "regardless": { bangla: "নির্বিশেষে", type: "adverb" },
  "regional": { bangla: "আঞ্চলিক", type: "adjective" },
  "regulate": { bangla: "নিয়ন্ত্রণ করা", type: "verb" },
  "regulation": { bangla: "নিয়ন্ত্রণ; বিধি", type: "noun" },
  "rehabilitation": { bangla: "পুনর্বাসন", type: "noun" },
  "reinforce": { bangla: "শক্তিশালী করা", type: "verb" },
  "reinforcement": { bangla: "শক্তিবৃদ্ধি", type: "noun" },
  "relationship": { bangla: "সম্পর্ক", type: "noun" },
  "relationships": { bangla: "সম্পর্ক", type: "noun" },
  "relax": { bangla: "বিশ্রাম নেওয়া", type: "verb" },
  "relevant": { bangla: "প্রাসঙ্গিক", type: "adjective" },
  "reliable": { bangla: "বিশ্বস্ত", type: "adjective" },
  "reliance": { bangla: "নির্ভরতা", type: "noun" },
  "remain": { bangla: "অবশিষ্ট থাকা", type: "verb" },
  "remote": { bangla: "দূরবর্তী", type: "adjective" },
  "renewable": { bangla: "নবায়নযোগ্য", type: "adjective" },
  "renovation": { bangla: "সংস্কার", type: "noun" },
  "rental": { bangla: "ভাড়া", type: "noun" },
  "replace": { bangla: "প্রতিস্থাপন করা", type: "verb" },
  "reputation": { bangla: "সুনাম", type: "noun" },
  "require": { bangla: "প্রয়োজন হওয়া", type: "verb" },
  "requirements": { bangla: "প্রয়োজনীয়তা", type: "noun" },
  "residential": { bangla: "আবাসিক", type: "adjective" },
  "residents": { bangla: "বাসিন্দা", type: "noun" },
  "resilience": { bangla: "স্থিতিস্থাপকতা", type: "noun" },
  "resolution": { bangla: "সমাধান", type: "noun" },
  "resources": { bangla: "সম্পদ", type: "noun" },
  "respect": { bangla: "সম্মান", type: "noun" },
  "respond": { bangla: "সাড়া দেওয়া", type: "verb" },
  "responsibility": { bangla: "দায়িত্ব", type: "noun" },
  "restrict": { bangla: "সীমাবদ্ধ করা", type: "verb" },
  "restriction": { bangla: "নিষেধাজ্ঞা", type: "noun" },
  "restrictions": { bangla: "নিষেধাজ্ঞা", type: "noun" },
  "retain": { bangla: "ধরে রাখা", type: "verb" },
  "retention": { bangla: "ধারণ", type: "noun" },
  "retirement": { bangla: "অবসর", type: "noun" },
  "revenue": { bangla: "রাজস্ব", type: "noun" },
  "reviews": { bangla: "পর্যালোচনা", type: "noun" },
  "reward": { bangla: "পুরস্কার", type: "noun" },
  "right": { bangla: "অধিকার", type: "noun" },
  "rights": { bangla: "অধিকার", type: "noun" },
  "risk": { bangla: "ঝুঁকি", type: "noun" },
  "risks": { bangla: "ঝুঁকি", type: "noun" },
  "routine": { bangla: "নিয়মিত কাজ", type: "noun" },
  "rural": { bangla: "গ্রামীণ", type: "adjective" },
  // ---- S ----
  "salary": { bangla: "বেতন", type: "noun" },
  "sanitation": { bangla: "স্যানিটেশন ব্যবস্থা", type: "noun" },
  "satellite": { bangla: "উপগ্রহ", type: "noun" },
  "satisfaction": { bangla: "সন্তুষ্টি", type: "noun" },
  "scale": { bangla: "মাপ; পরিসর", type: "noun" },
  "schedules": { bangla: "সময়সূচি", type: "noun" },
  "scholarships": { bangla: "বৃত্তি", type: "noun" },
  "schooling": { bangla: "বিদ্যালয় শিক্ষা", type: "noun" },
  "scientific": { bangla: "বৈজ্ঞানিক", type: "adjective" },
  "secondary": { bangla: "মাধ্যমিক", type: "adjective" },
  "security": { bangla: "নিরাপত্তা", type: "noun" },
  "sedentary": { bangla: "আসীন; নিষ্ক্রিয়", type: "adjective" },
  "sensitive": { bangla: "সংবেদনশীল", type: "adjective" },
  "severe": { bangla: "মারাত্মক", type: "adjective" },
  "shortage": { bangla: "ঘাটতি", type: "noun" },
  "significance": { bangla: "তাৎপর্য", type: "noun" },
  "significant": { bangla: "গুরুত্বপূর্ণ", type: "adjective" },
  "simultaneously": { bangla: "একই সাথে", type: "adverb" },
  "situation": { bangla: "পরিস্থিতি", type: "noun" },
  "situations": { bangla: "পরিস্থিতি", type: "noun" },
  "smuggling": { bangla: "চোরাচালান", type: "noun" },
  "socialise": { bangla: "সামাজিকীকরণ করা", type: "verb" },
  "software": { bangla: "সফটওয়্যার", type: "noun" },
  "solution": { bangla: "সমাধান", type: "noun" },
  "solutions": { bangla: "সমাধান", type: "noun" },
  "sophisticated": { bangla: "পরিশীলিত", type: "adjective" },
  "source": { bangla: "উৎস", type: "noun" },
  "sources": { bangla: "উৎস", type: "noun" },
  "species": { bangla: "প্রজাতি", type: "noun" },
  "specific": { bangla: "নির্দিষ্ট", type: "adjective" },
  "sponsorship": { bangla: "পৃষ্ঠপোষকতা", type: "noun" },
  "sportsmanship": { bangla: "খেলাধুলার মনোভাব", type: "noun" },
  "stability": { bangla: "স্থিতিশীলতা", type: "noun" },
  "standard": { bangla: "মান", type: "noun" },
  "standards": { bangla: "মান", type: "noun" },
  "status": { bangla: "মর্যাদা; অবস্থা", type: "noun" },
  "stereotypes": { bangla: "গতানুগতিক ধারণা", type: "noun" },
  "stimulation": { bangla: "উদ্দীপনা", type: "noun" },
  "strategy": { bangla: "কৌশল", type: "noun" },
  "streaming": { bangla: "অনলাইন সম্প্রচার", type: "noun" },
  "strength": { bangla: "শক্তি", type: "noun" },
  "strengthen": { bangla: "শক্তিশালী করা", type: "verb" },
  "stress": { bangla: "মানসিক চাপ", type: "noun" },
  "stressful": { bangla: "চাপপূর্ণ", type: "adjective" },
  "strict": { bangla: "কঠোর", type: "adjective" },
  "struggle": { bangla: "সংগ্রাম", type: "noun" },
  "subsequently": { bangla: "পরবর্তীতে", type: "adverb" },
  "subsidies": { bangla: "ভর্তুকি", type: "noun" },
  "substantial": { bangla: "যথেষ্ট পরিমাণ", type: "adjective" },
  "succeed": { bangla: "সফল হওয়া", type: "verb" },
  "success": { bangla: "সাফল্য", type: "noun" },
  "successful": { bangla: "সফল", type: "adjective" },
  "suffer": { bangla: "ভোগা; কষ্ট পাওয়া", type: "verb" },
  "sufficient": { bangla: "যথেষ্ট", type: "adjective" },
  "sugary": { bangla: "চিনিযুক্ত", type: "adjective" },
  "suitable": { bangla: "উপযুক্ত", type: "adjective" },
  "supervision": { bangla: "তত্ত্বাবধান", type: "noun" },
  "supplies": { bangla: "সরবরাহ", type: "noun" },
  "supportive": { bangla: "সহায়ক", type: "adjective" },
  "surgery": { bangla: "অস্ত্রোপচার", type: "noun" },
  "surveillance": { bangla: "নজরদারি", type: "noun" },
  "survival": { bangla: "টিকে থাকা", type: "noun" },
  "sustainability": { bangla: "টেকসইতা", type: "noun" },
  "sustainable": { bangla: "টেকসই", type: "adjective" },
  // ---- T ----
  "tackle": { bangla: "মোকাবেলা করা", type: "verb" },
  "talent": { bangla: "প্রতিভা", type: "noun" },
  "target": { bangla: "লক্ষ্য", type: "noun" },
  "taxation": { bangla: "কর ব্যবস্থা", type: "noun" },
  "teamwork": { bangla: "দলগত কাজ", type: "noun" },
  "techniques": { bangla: "কৌশল", type: "noun" },
  "technological": { bangla: "প্রযুক্তিগত", type: "adjective" },
  "teenagers": { bangla: "কিশোর-কিশোরী", type: "noun" },
  "temporarily": { bangla: "সাময়িকভাবে", type: "adverb" },
  "tension": { bangla: "উত্তেজনা; চাপ", type: "noun" },
  "tertiary": { bangla: "তৃতীয় স্তরের", type: "adjective" },
  "theft": { bangla: "চুরি", type: "noun" },
  "therapy": { bangla: "থেরাপি; চিকিৎসা", type: "noun" },
  "threat": { bangla: "হুমকি", type: "noun" },
  "threats": { bangla: "হুমকি", type: "noun" },
  "tolerance": { bangla: "সহনশীলতা", type: "noun" },
  "tourism": { bangla: "পর্যটন", type: "noun" },
  "tourist": { bangla: "পর্যটক", type: "noun" },
  "tradition": { bangla: "ঐতিহ্য", type: "noun" },
  "traditions": { bangla: "ঐতিহ্য", type: "noun" },
  "traffic": { bangla: "যানবাহন চলাচল", type: "noun" },
  "training": { bangla: "প্রশিক্ষণ", type: "noun" },
  "translate": { bangla: "অনুবাদ করা", type: "verb" },
  "translation": { bangla: "অনুবাদ", type: "noun" },
  "transparency": { bangla: "স্বচ্ছতা", type: "noun" },
  "transparent": { bangla: "স্বচ্ছ", type: "adjective" },
  "transportation": { bangla: "পরিবহন", type: "noun" },
  "treatment": { bangla: "চিকিৎসা", type: "noun" },
  "trend": { bangla: "প্রবণতা", type: "noun" },
  "truly": { bangla: "সত্যিই", type: "adverb" },
  "tuition": { bangla: "শিক্ষাদান", type: "noun" },
  // ---- U ----
  "ultimately": { bangla: "পরিশেষে", type: "adverb" },
  "uncertain": { bangla: "অনিশ্চিত", type: "adjective" },
  "unconventional": { bangla: "অপ্রচলিত", type: "adjective" },
  "undeniably": { bangla: "অনস্বীকার্যভাবে", type: "adverb" },
  "underlying": { bangla: "অন্তর্নিহিত", type: "adjective" },
  "undermine": { bangla: "ক্ষুণ্ন করা", type: "verb" },
  "underprepared": { bangla: "অপ্রস্তুত", type: "adjective" },
  "understanding": { bangla: "বোঝাপড়া", type: "noun" },
  "undoubtedly": { bangla: "নিঃসন্দেহে", type: "adverb" },
  "unemployment": { bangla: "বেকারত্ব", type: "noun" },
  "unequal": { bangla: "অসম", type: "adjective" },
  "unfair": { bangla: "অন্যায্য", type: "adjective" },
  "unique": { bangla: "অনন্য", type: "adjective" },
  "universe": { bangla: "মহাবিশ্ব", type: "noun" },
  "universities": { bangla: "বিশ্ববিদ্যালয়", type: "noun" },
  "university": { bangla: "বিশ্ববিদ্যালয়", type: "noun" },
  "unlikely": { bangla: "অসম্ভাব্য", type: "adjective" },
  "unnecessary": { bangla: "অপ্রয়োজনীয়", type: "adjective" },
  "unrealistic": { bangla: "অবাস্তব", type: "adjective" },
  "upbringing": { bangla: "লালন-পালন", type: "noun" },
  "urban": { bangla: "শহুরে", type: "adjective" },
  "urgently": { bangla: "জরুরিভাবে", type: "adverb" },
  "users": { bangla: "ব্যবহারকারী", type: "noun" },
  // ---- V ----
  "vacant": { bangla: "খালি", type: "adjective" },
  "vaccination": { bangla: "টিকাদান", type: "noun" },
  "valuable": { bangla: "মূল্যবান", type: "adjective" },
  "value": { bangla: "মূল্যবোধ", type: "noun" },
  "values": { bangla: "মূল্যবোধ", type: "noun" },
  "variety": { bangla: "বৈচিত্র্য", type: "noun" },
  "various": { bangla: "বিভিন্ন", type: "adjective" },
  "vehicle": { bangla: "যানবাহন", type: "noun" },
  "vehicles": { bangla: "যানবাহন", type: "noun" },
  "victim": { bangla: "শিকার", type: "noun" },
  "victims": { bangla: "শিকার", type: "noun" },
  "violence": { bangla: "সহিংসতা", type: "noun" },
  "violent": { bangla: "সহিংস", type: "adjective" },
  "visibility": { bangla: "দৃশ্যমানতা", type: "noun" },
  "visitors": { bangla: "দর্শনার্থী", type: "noun" },
  "vocational": { bangla: "বৃত্তিমূলক", type: "adjective" },
  "volunteering": { bangla: "স্বেচ্ছাসেবা", type: "noun" },
  "vulnerability": { bangla: "দুর্বলতা", type: "noun" },
  "vulnerable": { bangla: "ঝুঁকিপূর্ণ", type: "adjective" },
  // ---- W ----
  "wages": { bangla: "মজুরি", type: "noun" },
  "warming": { bangla: "উষ্ণায়ন", type: "noun" },
  "wealth": { bangla: "সম্পদ", type: "noun" },
  "welfare": { bangla: "কল্যাণ", type: "noun" },
  "wellbeing": { bangla: "সুস্থতা", type: "noun" },
  "widespread": { bangla: "ব্যাপক", type: "adjective" },
  "wildlife": { bangla: "বন্যপ্রাণী", type: "noun" },
  "workforce": { bangla: "শ্রমশক্তি", type: "noun" },
  "worldwide": { bangla: "বিশ্বব্যাপী", type: "adjective" },
  "worthwhile": { bangla: "সার্থক", type: "adjective" },
};
